#-------------------------------
# General Site Settings

title: Technical Anxiety | Experience Blog
description: A technical blog covering Azure, Log Analytics, leadership, and navigating anxiety in tech. Written by Jason Rinehart.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://technicalanxiety.com" # the base hostname & protocol for your site, e.g. http://example.com
lang: en_US

#-------------------------------
# About Section
author:
  name: Jason Rinehart
  avatar: me.jpg
  bio: Cloud architect and technical leader sharing experiences with Azure, leadership, and mental health in tech.
  twitter: anxiouslytech
  
# Legacy support (keeping for theme compatibility)
author-name: Jason Rinehart
author-avatar: me.jpg


#-------------------------------
# Social Media & SEO
# These are used for social sharing cards and SEO
twitter:
  username: anxiouslytech
  card: summary_large_image

# Social profile links (for theme)
#facebook:  https://facebook.com/ # Add your Facebook handle
twitter_url: https://twitter.com/anxiouslytech
#instagram: https://www.instagram.com/ # Add your Instagram handle
linkedin: https://linkedin.com/in/rinehart76

# Default social sharing image (1200x630px recommended)
# Place image in /img/ folder
social:
  name: Jason Rinehart
  links:
    - https://twitter.com/anxiouslytech
    - https://linkedin.com/in/rinehart76

# Default image for social sharing when post doesn't have one
# This appears when sharing posts that don't have a featured image
logo: /img/social-share-default.svg


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anxiouschat # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics 4 (GA4)
# Replace with your GA4 measurement ID (format: G-XXXXXXXXXX)
# Old Universal Analytics (UA-155892178-1) was deprecated July 2023
google-analytics: G-2HB2W9WDMR


#-------------------------------
# Newsletter (MailChimp)
# Uncomment and add your MailChimp form action URL to enable newsletter signup
# Get this from: MailChimp > Audience > Signup forms > Embedded forms
# mailchimp: https://technicalanxiety.us4.list-manage.com/subscribe/post?u=d98ffb1c29c62159ccdfc824c&amp;id=2e886e29d5


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
- _posts/backlog/
