#-------------------------------
# General Site Settings

title: Technical Anxiety | Experience Blog
description: A technical blog covering Azure, Log Analytics, leadership, and navigating anxiety in tech. Written by Jason Rinehart.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://technicalanxiety.com" # the base hostname & protocol for your site, e.g. http://example.com
lang: en_US

#-------------------------------
# About Section
author:
  name: Jason Rinehart
  avatar: me.jpg
  bio: Cloud architect and technical leader sharing experiences with Azure, leadership, and mental health in tech.
  
# Legacy support (keeping for theme compatibility)
author-name: Jason Rinehart
author-avatar: me.jpg


#-------------------------------
# Contact links
#facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/anxiouslytech # Add your Facebook handle
#instagram: https://www.instagram.com/ # Add your Facebook handle
linkedin: https://linkedin.com/in/rinehart76 # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anxiouschat # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics 4 (GA4)
# Replace with your GA4 measurement ID (format: G-XXXXXXXXXX)
# Old Universal Analytics (UA-155892178-1) was deprecated July 2023
google-analytics: # G-2HB2W9WDMR


#-------------------------------
# Newsletter
# mailchimp: https://technicalanxiety.us4.list-manage.com/subscribe/post?u=d98ffb1c29c62159ccdfc824c&amp;id=2e886e29d5 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
- _posts/backlog/
